version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: epowweb
      POSTGRES_USER: epowweb
      POSTGRES_PASSWORD: epowweb
    ports:
      - "5432:5432"
    volumes:
      - pgdata_epowweb:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "epowweb"]
      interval: 5s
      retries: 5
      start_period: 5s
      timeout: 5s

volumes:
  pgdata_epowweb:
